import os
import streamlit as st

from utils.data_loader import load_pipeline_monthly, load_deals
from utils.ai_recommendations import compute_ai_recommendations
from utils.sales_agent import build_context, ask_agent, generate_exec_summary

st.set_page_config(page_title="AI Workflow Agent", page_icon="🤖", layout="wide")

# Bridge the API key from Streamlit secrets to env vars for the agent module.
try:
    if "ANTHROPIC_API_KEY" in st.secrets:
        os.environ["ANTHROPIC_API_KEY"] = st.secrets["ANTHROPIC_API_KEY"]
    if "CLAUDE_MODEL" in st.secrets:
        os.environ["CLAUDE_MODEL"] = st.secrets["CLAUDE_MODEL"]
except Exception:
    pass

st.title("🤖 AI Workflow Agent")
st.caption(
    "Ask questions about the NA VAS pipeline in plain English, or generate an "
    "executive summary — grounded in the dashboard's data."
)

pipeline_df = load_pipeline_monthly()
deals_df = load_deals()
recommendations = compute_ai_recommendations(deals_df)
context = build_context(pipeline_df, deals_df, recommendations)

with st.expander("What the agent can see (grounding data)"):
    st.text(context)

if st.button("Generate executive summary", type="primary"):
    with st.spinner("Generating…"):
        try:
            summary = generate_exec_summary(context)
        except Exception as exc:
            st.error(f"Could not generate summary: {exc}")
        else:
            st.markdown(summary)

st.divider()
st.subheader("Ask the agent")

if "agent_messages" not in st.session_state:
    st.session_state.agent_messages = []

for m in st.session_state.agent_messages:
    with st.chat_message(m["role"]):
        st.markdown(m["content"])

prompt = st.chat_input("e.g., Which product has the weakest win rate, and what should we do?")
if prompt:
    st.session_state.agent_messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)
    with st.chat_message("assistant"):
        with st.spinner("Thinking…"):
            try:
                answer = ask_agent(prompt, context)
            except Exception as exc:
                answer = f"Sorry — I couldn't answer that: {exc}"
            st.markdown(answer)
    st.session_state.agent_messages.append({"role": "assistant", "content": answer})

st.caption(
    "Answers are generated by Claude grounded in the figures above — for "
    "demonstration; not financial advice."
)
